### ISSUE TITLE
featreg to first vol instead of middle?

### ISSUE THREAD

**Issue by gciccarelli3** [gablab/openfmri#19]
Why this design choice when the default is middle?

preproc = create_featreg_preproc(whichvol='first')

def create_featreg_preproc(name='featpreproc', highpass=True, whichvol='middle'):
https://github.com/nipy/nipype/blob/master/nipype/workflows/fmri/fsl/preprocess.py

**Comment by satra** [comment]
mostly because the first volume of the first run is one where a participant may be more stationary on average. this is not an empirically validated statement, but a judgment based on imaging experience across adults and kids.

note that this will change to some average volume with the upcoming changes to the l1 script.
